### ISSUE TITLE
Support arbitrary scores and ratings

### ISSUE THREAD

**Issue by nllong** [BuildingSync/schema#152]
There needs to be a general solution for storing arbitrary scores and ratings by premises and floor areas.

**Comment by nllong** [comment]
@markborkum do you want to take a stab at solving this?

**Comment by markborkum** [comment]
@nllong Sounds good, thanks.

**Comment by nllong** [comment]
I think #163 has addressed a portion of this.

**Comment by markborkum** [comment]
@nllong For the other premises levels, I'm considering the following:

1. Pluralize `auc:Benchmark` (so that it is harmonized with `auc:Assessments`/`auc:Assessment`).
2. Add `auc:LinkedPremises` to `auc:Benchmark`.

(1) is a breaking change; however, end-users can still assert that the `auc:ScenarioType` is benchmarking, e.g.,

```
<auc:Scenario>
  <auc:ScenarioType>
    <auc:Benchmarks/>
  </auc:ScenarioType>
</auc:Scenario>
```

(2) is non-breaking, e.g.,

```
<auc:Benchmark>
  <auc:LinkedPremises>
    <auc:Section>
      <auc:LinkedSectionID IDref="Section1"/>
    </auc:Section>
  </auc:LinkedPremises>
</auc:Benchmark>
```

The benefit of (1) is that a given `auc:Scenario` can provide the time-series data and scores/ratings for multiple benchmarks. Otherwise, (2) would require one `auc:Scenario` for each benchmark.

**Comment by nllong** [comment]
I'm leaning towards implementing option 2 only. Are there many cases where the time-series data will be redundant across multiple scores/ratings?

**Comment by markborkum** [comment]
@nllong In Audit Template, no cases that I am aware of.

See https://github.com/BuildingSync/schema/pull/164 for the PR for option 2.

**Comment by nllong** [comment]
Let me release the next prerelease of 2.0 tomorrow morning and then we can discuss handling option 1.
