### ISSUE TITLE
BuldingSync and HPXML

### ISSUE THREAD

**Issue by mioruggieroguida** [BuildingSync/schema#455]
This is not an issue, but more a question. Apologies if this is not the right place, but I could not find a forum or community for discussions related to BuildingSync.

We are a new startup in the proptech/climatetech space and we are evaluating several schemas to describe our bulding models.

First of all I would like to say thank you for this amazing work. I believe that efforts such as BuildingSync will change our industry and make it fit for the immense decarbonization challenge ahead of us.

I have read [this](https://www.sciencedirect.com/science/article/pii/S2666165921000132) paper and you also mention HPXML that, as I understand, was developed before BuildingSync.

Do you think BuildingSync could be used as a replacement for or superset of HPXML? Maybe with some extension or some custom field? The reason I ask is becasue it would be great to be able to reduce the number of schemas that we have to use. My background is building services and energy modelling so I tend to see residential buildings just as buildings with different systems, loads, schedules, etc.. 

Thanks
Ruggiero Guida
CTO
Mortar IO

**Comment by laurenliz22** [comment]
Hello Ruggiero

Congratulations on your new start up!  While I do agree it would be nice to have less schemas out there, at this time there is unfortunately no plan to use BuildingSync as a replacement for HPXML since BuildingSync was generated specifically for commercial buildings.  We are continuing to grow the schema to include decarbonization metrics as new legislative requirements are being established for commercial buildings.  Please stay in touch if you have any additional questions on how BuildingSync works.  You should also join our community forum at https://lists.buildingenergytools.org/g/BuildingSync.

Thank you!
Lauren Adams
NREL
